name = "ndc-elections-api"
main = "dist/index.mjs"
usage_model = 'bundled'
workers_dev = true
compatibility_date = "2023-09-10"

[build]
command = "yarn install && yarn build"

[vars]
# The necessary secrets are:
# - PIKESPEAK_API_KEY
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these

[durable_objects]
bindings = [{ name = "CANDIDATES", class_name = "Candidates" }]

[triggers]
crons = ["*/2 * * * *"]

[[migrations]]
tag = "v1"
new_classes = ["Candidates"]

[[migrations]]
tag = "v2"
deleted_classes = ["Candidates"]

[[migrations]]
tag = "v3"
new_classes = ["Candidates"]

[[migrations]]
tag = "v4"
deleted_classes = ["Candidates"]

[[migrations]]
tag = "v5"
new_classes = ["Candidates"]

[[migrations]]
tag = "v6"
deleted_classes = ["Candidates"]

[[migrations]]
tag = "v7"
new_classes = ["Candidates"]

[[migrations]]
tag = "v8"
deleted_classes = ["Candidates"]

[[migrations]]
tag = "v9"
new_classes = ["Candidates"]

[[migrations]]
tag = "v10"
deleted_classes = ["Candidates"]

[[migrations]]
tag = "v11"
new_classes = ["Candidates"]

[[migrations]]
tag = "v12"
deleted_classes = ["Candidates"]

[[migrations]]
tag = "v13"
new_classes = ["Candidates"]

[[migrations]]
tag = "v14"
deleted_classes = ["Candidates"]

[[migrations]]
tag = "v15"
new_classes = ["Candidates"]
